# Generated by Django 4.1.7 on 2023-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AZ', 'Azerbaijan'), ('RU', 'Russia'), ('TR', 'Turkey'), ('UK', 'United Kingdom')], max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
                ('adress_line', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('coniform_password', models.CharField(max_length=30)),
            ],
        ),
    ]
