# Generated by Django 4.1.7 on 2023-07-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_ips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_Adress',
        ),
    ]
