# Generated by Django 4.1.7 on 2023-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_shipping_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/images/images.jpeg', null=True, upload_to='media/user_profile'),
        ),
    ]
