version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
      
    volumes:
      - ./pgdb:/var/lib/postgresql/data

  web:
    container_name: multikart
    build: .
    ports:
      - 8002:8000
    depends_on:
      - "db"
      - "redis"
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    env_file:
      - .env
      

  celery:
    container_name: celery
    command: celery -A multikart worker -l info -B
    build: 
      context: .
      dockerfile: celery.dockerfile
    depends_on: 
      - "db"
      - "redis"
    environment:
      REDIS_HOST : redis



  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  localnetworks:
      name: nginx-proxy
      external: True
            