# Generated by Django 4.1.7 on 2023-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='advert_images')),
            ],
        ),
    ]
