# Generated by Django 4.1.7 on 2023-05-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_accesories_accesoriesimage_console_consoleimages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accesories',
            new_name='Accesorie',
        ),
    ]
