# Generated by Django 4.1.7 on 2023-05-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_accesories_accesorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesoriesImage',
            new_name='AccesorieImage',
        ),
        migrations.RenameModel(
            old_name='ConsoleImages',
            new_name='ConsoleImage',
        ),
        migrations.RenameModel(
            old_name='GameImages',
            new_name='GameImage',
        ),
        migrations.RenameModel(
            old_name='VendorImages',
            new_name='VendorImage',
        ),
        migrations.AlterModelOptions(
            name='accesorie',
            options={'verbose_name': 'Accesorie', 'verbose_name_plural': 'Accesories'},
        ),
        migrations.AlterModelOptions(
            name='accesorieimage',
            options={'verbose_name': 'Accesorie Image', 'verbose_name_plural': 'Accesorie Images'},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={'verbose_name': 'Console', 'verbose_name_plural': 'Consoles'},
        ),
        migrations.AlterModelOptions(
            name='consoleimage',
            options={'verbose_name': 'Console Image', 'verbose_name_plural': 'Console Images'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'verbose_name': 'Game Category', 'verbose_name_plural': 'Game Categories'},
        ),
        migrations.AlterModelOptions(
            name='gameimage',
            options={'verbose_name': 'Game Image', 'verbose_name_plural': 'Game Images'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendorimage',
            options={'verbose_name': 'Vendor Image', 'verbose_name_plural': 'Vendor Images'},
        ),
    ]
