# Generated by Django 4.1.7 on 2023-05-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='product.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='storage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_id', to='product.storage', verbose_name='Storage'),
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_image', models.ImageField(upload_to='vendor_images')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_images', to='product.vendor')),
            ],
        ),
    ]
