# Generated by Django 4.1.7 on 2023-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='slug'),
        ),
    ]
