# Generated by Django 4.1.7 on 2023-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productversion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
