# Generated by Django 4.1.7 on 2023-07-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productversion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='review_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_url', to='product.review', verbose_name='comment'),
        ),
    ]
