# Generated by Django 4.1.7 on 2023-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productversion_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='review_id',
        ),
        migrations.AlterField(
            model_name='productversion',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
