# Generated by Django 4.1.7 on 2023-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_productversion_review_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productversion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
    ]
