# Generated by Django 4.1.7 on 2023-07-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='product.productcategory', verbose_name='Parent Category'),
        ),
    ]
