# Generated by Django 4.1.7 on 2023-07-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
