# Generated by Django 4.1.7 on 2023-05-21 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
