# Generated by Django 4.1.7 on 2023-07-08 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='postal_code',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='last_name',
        ),
        migrations.AddField(
            model_name='checkout',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
