# Generated by Django 4.1.7 on 2023-07-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productversion_stock'),
        ('order', '0005_remove_checkout_country_remove_checkout_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productimage'),
        ),
    ]
