# Generated by Django 4.1.7 on 2023-07-12 20:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
